### ISSUE TITLE
Micro frontend

### ISSUE THREAD

**Issue by rpmolina** [nanlabs/frontend-reference#12]
### Describe the feature
To start with the concepts of this topic, it is good to read the [article](https://martinfowler.com/articles/micro-frontends.html). 
The idea of this issues, is use the following techs:

* Webpack module federation (you can check this [course](https://www.udemy.com/course/microfrontend-course/learn/lecture/24615508#overview) out).
* vite (@originjs/vite-plugin-federation).

The ideal path for this research is complete the following steps using the above techs:

* [x] nanlabs/frontend-reference#11
* [x] nanlabs/frontend-reference#10
* [x] nanlabs/frontend-reference#9
* [x] nanlabs/frontend-reference#8
* [ ] nanlabs/frontend-reference#7

### Use Case
use as refereces 

### Acknowledgements
* [ ] I may be able to implement this feature request
* [ ] This feature might incur a breaking change

### Version used
* 

### Environment details (OS name and version, etc.)
-

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/85ztrkpb9) by [Unito](https://www.unito.io)
